In [20]:
import tensorflow as tf
import tensorflow.keras as k
from inefficient_networks.config import config

(x_train, y_train), (x_test, y_test) = k.datasets.mnist.load_data()

In [40]:
config.set_tensorflow_seeds(4)
model = k.Sequential()
model.add(k.layers.Dense(512, 'relu'))
model.add(k.layers.Dense(10))

model.compile(
    metrics='accuracy',
    optimizer='adam',
    loss=k.losses.SparseCategoricalCrossentropy()
)

model.fit(x_train.reshape(-1, 784), y_train, epochs=2, batch_size=32)

Epoch 1/2
  24/1875 [..............................] - ETA: 8s - loss: 11.4690 - accuracy: 0.0964

2022-04-11 17:16:04.240699: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.


1875/1875 [==============================] - 9s 5ms/step - loss: 14.0938 - accuracy: 0.1065
Epoch 2/2
1875/1875 [==============================] - 10s 5ms/step - loss: 13.7638 - accuracy: 0.1164


In [41]:
config.set_tensorflow_seeds(4)
model = k.Sequential()
model.add(k.layers.Dense(512, 'relu'))
model.add(k.layers.Dense(10, 'softmax'))

model.compile(
    metrics='accuracy',
    optimizer='adam',
    loss=k.losses.SparseCategoricalCrossentropy(from_logits=True)
)

model.fit(x_train.reshape(-1, 784), y_train, epochs=2, batch_size=32)

Epoch 1/2
  12/1875 [..............................] - ETA: 8s - loss: 60.0240 - accuracy: 0.4635   

/Users/particle1331/miniforge3/envs/ml/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py:1096: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a sigmoid or softmax activation and thus does not represent logits. Was this intended?"
  return dispatch_target(*args, **kwargs)
2022-04-11 17:16:24.819628: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.


1875/1875 [==============================] - 9s 5ms/step - loss: 2.6508 - accuracy: 0.9084
Epoch 2/2
1875/1875 [==============================] - 9s 5ms/step - loss: 0.3410 - accuracy: 0.9387


In [37]:
tf.reduce_sum(model(x_train.reshape(-1, 784))[3])
# model.fit(x_train.reshape(-1, 784), y_train, epochs=2, batch_size=32)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [36]:
k.activations.softmax(model(x_train.reshape(-1, 784)))[3]


<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.08533674, 0.23196931, 0.08533674, 0.08533674, 0.08533674,
       0.08533674, 0.08533674, 0.08533674, 0.08533674, 0.08533674],
      dtype=float32)>

In [26]:
k.activations.sigmoid(model(x_test.reshape(-1, 784)))

<tf.Tensor: shape=(10000, 10), dtype=float32, numpy=
array([[0.7292609 , 0.7308539 , 0.73105   , ..., 0.7310586 , 0.5020167 ,
        0.73105705],
       [0.5037693 , 0.7305503 , 0.7310586 , ..., 0.7309286 , 0.7166949 ,
        0.50014967],
       [0.7310481 , 0.7310586 , 0.50360113, ..., 0.7310525 , 0.7310585 ,
        0.72551274],
       ...,
       [0.5       , 0.50000006, 0.5       , ..., 0.5352798 , 0.5000821 ,
        0.7310584 ],
       [0.7310586 , 0.7296226 , 0.73102   , ..., 0.7117257 , 0.7310586 ,
        0.7310539 ],
       [0.7310586 , 0.5000198 , 0.7310418 , ..., 0.5000738 , 0.7310586 ,
        0.7268566 ]], dtype=float32)>